export const endpoints = {
  products: {
    list: "/products",
    detail: (id: string) => `/products/${id}`,
    create: "/products",
    update: (id: string) => `/products/${id}`,
    remove: (id: string) => `/products/${id}`,
    duplicate: (id: string) => `/products/${id}/duplicate`,
  },
  banners: {
    list: "/banners",
    detail: (id: string) => `/banners/${id}`,
    create: "/banners",
    update: (id: string) => `/banners/${id}`,
    remove: (id: string) => `/banners/${id}`,
    analytics: "/banners/analytics",
  },
  videos: {
    list: "/videos",
    detail: (id: string) => `/videos/${id}`,
    create: "/videos",
    update: (id: string) => `/videos/${id}`,
    remove: (id: string) => `/videos/${id}`,
  },
  seo: {
    overview: "/seo/overview",
    pages: "/seo/pages",
    redirects: "/seo/redirects",
    sitemap: "/seo/sitemap",
  },
  orders: {
    list: "/orders",
    detail: (id: string) => `/orders/${id}`,
    update: (id: string) => `/orders/${id}`,
    invoice: (id: string) => `/orders/${id}/invoice`,
  },
  customers: {
    list: "/customers",
    detail: (id: string) => `/customers/${id}`,
    update: (id: string) => `/customers/${id}`,
  },
  reviews: {
    list: "/reviews",
    detail: (id: string) => `/reviews/${id}`,
    approve: (id: string) => `/reviews/${id}/approve`,
    reject: (id: string) => `/reviews/${id}/reject`,
  },
  queries: {
    list: "/contact-queries",
    detail: (id: string) => `/contact-queries/${id}`,
    reply: (id: string) => `/contact-queries/${id}/reply`,
  },
  users: {
    list: "/users",
    detail: (id: string) => `/users/${id}`,
    create: "/users",
    update: (id: string) => `/users/${id}`,
    roles: "/roles",
    activity: "/users/activity",
  },
  dashboard: {
    overview: "/dashboard/overview",
    revenue: "/dashboard/revenue",
    orders: "/dashboard/orders",
    customers: "/dashboard/customers",
  },
  settings: {
    general: "/settings/general",
    website: "/settings/website",
    notifications: "/settings/notifications",
    payments: "/settings/payments",
    shipping: "/settings/shipping",
  },
} as const;
