export const ROUTES = {
  HOME: "/",
  DASHBOARD: "/dashboard",
  PRODUCTS: "/products",
  PRODUCT_NEW: "/products/new",
  PRODUCT_EDIT: (id = ":id") => `/products/${id}/edit`,
  PRODUCT_DETAILS: (id = ":id") => `/products/${id}`,
  BANNERS: "/banners",
  BANNER_NEW: "/banners/new",
  BANNER_EDIT: (id = ":id") => `/banners/${id}/edit`,
  BANNER_ANALYTICS: "/banners/analytics",
  VIDEOS: "/videos",
  VIDEO_NEW: "/videos/new",
  VIDEO_EDIT: (id = ":id") => `/videos/${id}/edit`,
  REELS: "/videos/reels",
  VIDEO_ANALYTICS: "/videos/analytics",
  SEO: "/seo",
  SEO_META: "/seo/meta",
  SEO_REDIRECTS: "/seo/redirects",
  SEO_SITEMAP: "/seo/sitemap",
  ORDERS: "/orders",
  ORDER_DETAILS: (id = ":id") => `/orders/${id}`,
  ORDER_INVOICE: (id = ":id") => `/orders/${id}/invoice`,
  CUSTOMERS: "/customers",
  CUSTOMER_DETAILS: (id = ":id") => `/customers/${id}`,
  REVIEWS: "/reviews",
  TESTIMONIALS: "/reviews/testimonials",
  QUERIES: "/queries",
  QUERY_DETAILS: (id = ":id") => `/queries/${id}`,
  USERS: "/users",
  USER_NEW: "/users/new",
  ROLES: "/users/roles",
  ACTIVITY_LOGS: "/users/activity",
  SETTINGS: "/settings",
  SETTINGS_GENERAL: "/settings/general",
  SETTINGS_WEBSITE: "/settings/website",
  SETTINGS_NOTIFICATIONS: "/settings/notifications",
  SETTINGS_PAYMENTS: "/settings/payments",
  SETTINGS_SHIPPING: "/settings/shipping",
  NOT_FOUND: "*",
} as const;
